name: mesazon-droplets-ci
on:
  push:
    branches: [ main ]
    paths:
      - ".github/**"
      - 'mesazon-droplets/**'
      - 'modules/**'
  pull_request:
    paths:
      - ".github/**"
      - 'mesazon-droplets/**'
      - 'modules/**'
jobs:
  mesazon-droplets-dev-tf-plan:
    uses: ./.github/workflows/tf-plan.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d9"
      working-directory: "mesazon-droplets/environments/dev"
      module: "mesazon-droplets-dev"

  mesazon-droplets-dev-tf-apply:
    needs: [ "mesazon-droplets-dev-tf-plan" ]
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d9"
      working-directory: "mesazon-droplets/environments/dev"
      module: "mesazon-a-dev"
      environment: "dev"

# Example of how to add prod environment deployment after dev is successful
#  mesazon-clusters-prod-tf-plan:
#    needs: [ "mesazon-clusters-dev-tf-apply" ]
#    if: github.ref == 'refs/heads/main'
#    uses: ./.github/workflows/tf-plan.yml
#    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
#    with:
#      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d8"
#      working-directory: "mesazon-clusters/environments/prod"
#      module: "mesazon-clusters-prod"
#
#  mesazon-clusters-prod-tf-apply:
#    needs: [ "mesazon-clusters-prod-tf-plan" ]
#    if: github.ref == 'refs/heads/main'
#    uses: ./.github/workflows/tf-apply.yml
#    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
#    with:
#      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d8"
#      working-directory: "mesazon-clusters/environments/prod"
#      module: "mesazon-clusters-prod"
#      environment: "prod"
