name: mesazon-vpc-ci
on:
  push:
    branches: [ main ]
    paths:
      - ".github/**"
      - 'mesazon-vpc/**'
      - 'modules/**'
  pull_request:
    paths:
      - ".github/**"
      - 'mesazon-vpc/**'
      - 'modules/**'
jobs:
  mesazon-vpc-dev-tf-plan:
    uses: ./.github/workflows/job-tf-plan.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: ""
      working-directory: "mesazon-vpc/dev"
      module: "mesazon-vpc-dev"

  mesazon-vpc-dev-tf-apply:
    needs: [ "mesazon-vpc-dev-tf-plan" ]
    if: needs.mesazon-vpc-dev-tf-plan.outputs.changes-detected == 'true'
    uses: ./.github/workflows/job-tf-apply.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: ""
      working-directory: "mesazon-vpc/dev"
      module: "mesazon-vpc-dev"
      environment: "dev"

# Example of how to add prod environment deployment after dev is successful
#  mesazon-vpc-prod-tf-plan:
#    needs: [ "mesazon-vpc-dev-tf-apply" ]
#    if: github.ref == 'refs/heads/main'
#    uses: ./.github/workflows/job-tf-plan.yml
#    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
#    with:
#      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d8"
#      working-directory: "mesazon-vpc/environments/prod"
#      module: "mesazon-vpc-prod"
#
#  mesazon-vpc-prod-tf-apply:
#    needs: [ "mesazon-vpc-prod-tf-plan" ]
#    if: github.ref == 'refs/heads/main'
#    uses: ./.github/workflows/job-tf-apply.yml
#    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
#    with:
#      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d8"
#      working-directory: "mesazon-vpc/environments/prod"
#      module: "mesazon-vpc-prod"
#      environment: "prod"
