name: terraform-apply
on:
  workflow_call:
    inputs:
      module-dir:
        description: "Module directory"
        type: string
        required: true
      org:
        description: "Organization name"
        type: string
        required: true
      project:
        description: "Project name 'mesazon-dev, mesazon-prod, etc'"
        type: string
        required: true
      env:
        description: "Environment 'dev, prod, etc'"
        type: string
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_do_token: ${{ secrets.DO_API_KEY }}
jobs:
  build:
    environment: terraform-apply-approval
    name: Terraform apply for ${{ inputs.project }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
      - name: Terraform Init
        id: init
        run: |
          terraform init
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
